### PR TITLE
Parsimony permission issue! write access to var

### PR DESCRIPTION
**Pull request by stblackbird**
In my environment parsimony didn't work after installation. The issue was the write access to "var/" folder was needed. After that all is fine (nice project btw!)

I just changed install.php to require write access to var/

### CODE REVIEW

**Comment by parsimony** [comment]
Hello
I understand your commit.
Install.php no longer exists. It is modified and renamed installNewLife.php.
This issue doesn't exist in a new project with current sources.

Perhaps your Parsimony project was older than the "var" folder & installNewLife.php commit (?)
Thank you for feedback

**Comment by stblackbird** [comment]
oO I used the 2.5 release. I usely do this since I have the idea that the version in release state should be the one to use.
Ok, you can close this if you want and I will use the latest files, but can you release a new version of your script too?

**Comment by parsimony** [comment]
Ok, could you please confirm it works with lastest files in the master branch before closing this pull request ? ( https://github.com/parsimony/parsimony_cms/archive/master.zip )
We are working hard for 10 month to release a great 3.0 version, this release is expected to be available in early 2014.

**Comment by stblackbird** [comment]
Sorry that it took me so long to comment, simple forgot it... Anyway my feedback about Permissions

The permissions system is not perfect yet. Parsimony requires read/write on "var" folder too, while it doesn't say so during installation. If you try to install without giving access, installation fails

One minor thing, folder "profiles" must be created by the user. It is not included in the zip file

One more minor thing is that during installation parsimony asks the user to change permission to Index.php, InstallNewLife.php. In my opinion it shouldn't capitalize the first letters.

**Comment by parsimony** [comment]
Ok, we just updated the installer : 
- we added a check for var/ foder read/write permissions
- first letter of installNewLife.php is no more capitilized

For the profiles/ folder, it mustn't be created by the user but by the installer when copying the default config file.

Do you think that it's ok ?

Thanks a lot :+1:

**Comment by stblackbird** [comment]
> One minor thing, folder "profiles" must be created by the user. It is not included in the zip file

I meant "has to be" instead of must be. I tested the last version and everything seems OK! Thanks

We can close this request

**Comment by parsimony** [comment]
Thanks for your contribution :+1:

**Pull request closed without merging**
